### ISSUE TITLE
Lien 'cassé' pour les fiches individuelle d'enregistrement

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-hub#1]
Après une recherche basique/classique (sur les tortues et après sur les "felix"), les fiches individuelles d'enregistrements dans l'onglets "Records" 
![rapport_erreur_1](https://cloud.githubusercontent.com/assets/12632799/14630899/e05c439a-0610-11e6-824d-4b800c7b29c1.PNG)

amènent sur une erreur 404 lorsqu'on essaie de les consulter

![rapport_erreur_2](https://cloud.githubusercontent.com/assets/12632799/14630898/e05bdcc0-0610-11e6-9cb6-53d85174e928.PNG)

**Comment by CaviereFabien** [comment]
J'ai trouvé une occurence pour laquelle je peux voir la fiche d'enregistrement : http://recherche.gbif.fr/occurrences/a5187cff-fd92-4f82-85ef-222a62cfdd46
![rapport_1](https://cloud.githubusercontent.com/assets/12632799/14637934/eb3a92ca-0634-11e6-95d4-6b04d45f1bdf.png)

**Comment by melecoq** [comment]
<img width="1222" alt="screen shot 2016-04-19 at 16 38 53" src="https://cloud.githubusercontent.com/assets/3941231/14659021/3b1e0020-064d-11e6-8cef-9d25489896e5.png">
Version 1.16 (disponible sur VM)
