### ISSUE TITLE
Fenêtre de téléchargement des données

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-hub#10]
Toute la fenêtre est en anglais

Le chemin a été : http://185.26.127.140/generic-hub/occurrences/search?taxa=asio#tab_recordsView -> Downloads

![capture_31](https://cloud.githubusercontent.com/assets/12632799/14642620/7350f2ba-064b-11e6-87eb-b418d95e53c2.PNG)

**Comment by melecoq** [comment]
![screen shot 2016-05-10 at 11 30 48](https://cloud.githubusercontent.com/assets/3941231/15157956/acb05eda-16a2-11e6-8434-51644341ac1c.png)

Fixed on VM-7
