### ISSUE TITLE
"Données d'origine vs données traitée" 

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-hub#12]
Test avec Ubuntu et Chromium & Firefox :
Lors du clic sur ce bouton (http://recherche.gbif.fr/occurrences/a5187cff-fd92-4f82-85ef-222a62cfdd46), on a une fenêtre qui s'affiche sur 1/3 de l'écran
![capture_15](https://cloud.githubusercontent.com/assets/12632799/14639291/2e14cb2c-063c-11e6-8e5d-c1552813a5c8.png)

**Comment by melecoq** [comment]
<img width="1090" alt="screen shot 2016-04-19 at 16 05 10" src="https://cloud.githubusercontent.com/assets/3941231/14658415/8253c18c-0648-11e6-8350-f66a73bcd6ff.png">
Version 1.16 (disponible sur VM)
