### ISSUE TITLE
Lien "Retour aux résultats de la recherche" inopérant

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-hub#13]
Dans la fiche d'un enregistrement (http://recherche.gbif.fr/occurrences/ada382ad-38ec-481d-8692-b6da87f8ed9a#), le lien ne fait que renvoyer l'utilisateur sur la page courante
![capture_16](https://cloud.githubusercontent.com/assets/12632799/14639889/37fd870c-063f-11e6-8cb0-708f982ec52b.PNG)

**Comment by melecoq** [comment]
<img width="1237" alt="screen shot 2016-05-10 at 10 06 38" src="https://cloud.githubusercontent.com/assets/3941231/15155518/b60fb256-1697-11e6-95ad-b9e7e68c160b.png">

Same as #25.
Fixed on VM-2
