### ISSUE TITLE
Textes dans la personnalisation des filtres

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-hub#14]
Dans le résultat d'une recherche, le texte affiché pour l'option "Personnaliser les filtres"  est en anglais
![capture_19](https://cloud.githubusercontent.com/assets/12632799/14640508/17932622-0642-11e6-91f5-02bfa758c564.PNG)

**Comment by melecoq** [comment]
![screen shot 2016-05-10 at 11 26 36](https://cloud.githubusercontent.com/assets/3941231/15157812/15c2e790-16a2-11e6-899f-ca6ab00d3a30.png)

Fixed on VM-2
