### ISSUE TITLE
Texte de la page des résultats d'une recherche

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-hub#16]
Ce qui est en anglais :
- la ligne des nombres en haut
- la ligne des filtres (juste en dessous)
- les intitulés des onglets
- l'intitulé du bouton/lien de téléchargement
- les options de visualisations de la recherche (ordre croissant, combien d'occurence à afficher, etc...)

![capture_20](https://cloud.githubusercontent.com/assets/12632799/14640807/943700e4-0643-11e6-94f6-4fc0f8a7eef4.PNG)
- le menu des filtres (menu de gauche)
- les options de la carte

![capture_37](https://cloud.githubusercontent.com/assets/12632799/14643209/bac10200-064d-11e6-92d6-cce269fa2ac5.PNG)

**Comment by melecoq** [comment]
<img width="346" alt="screen shot 2016-05-11 at 21 17 16" src="https://cloud.githubusercontent.com/assets/3941231/15204011/ce219338-17bd-11e6-86e7-2f5d8aded9c0.png">

**Comment by melecoq** [comment]
<img width="1179" alt="screen shot 2016-05-12 at 21 43 36" src="https://cloud.githubusercontent.com/assets/3941231/15238239/9ceb74f0-188a-11e6-8f35-c4c557c859e8.png">
<img width="1042" alt="screen shot 2016-05-12 at 21 43 29" src="https://cloud.githubusercontent.com/assets/3941231/15238240/9cebddb4-188a-11e6-89e1-e054bcce1dce.png">

Fixed on VM-2
