### ISSUE TITLE
Partie de recherche

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-hub#17]
Dans la page de résultats d'une recherche, en haut à droite, la partie 'Nouvelle recherche' est en anglais
![capture_21](https://cloud.githubusercontent.com/assets/12632799/14640857/d2b78b40-0643-11e6-8636-7e22b28b3437.PNG)

**Comment by melecoq** [comment]
<img width="340" alt="screen shot 2016-05-10 at 10 11 29" src="https://cloud.githubusercontent.com/assets/3941231/15155504/96a22c64-1697-11e6-9431-8b7e49851177.png">

Fixed on VM-2
