### ISSUE TITLE
Carte dans les résultats de recherche

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-hub#18]
Aucun point n'apparait (j'ai essayé avec des catégories dans les recherches avancés, avec Canis lupus, etc...)

![capture_38](https://cloud.githubusercontent.com/assets/12632799/14643285/2674509c-064e-11e6-8c3a-854a4d4f5b75.PNG)

**Comment by melecoq** [comment]
![screen shot 2016-04-19 at 16 41 06](https://cloud.githubusercontent.com/assets/3941231/14659066/8c6c215a-064d-11e6-9186-d63c6e3a823a.png)

Version 1.16 (disponible sur VM)

Demain, je mettrais peut être à jour la version en production
