### ISSUE TITLE
Lien dans la partie affichage par diagramme

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-hub#19]
Le lien en haut à droite mériterai un CSS pour le mettre en valeur

![capture_39](https://cloud.githubusercontent.com/assets/12632799/14643991/cfe1fd12-0650-11e6-8a29-bb11f7ff3714.PNG)

**Comment by melecoq** [comment]
<img width="859" alt="screen shot 2016-05-11 at 21 16 18" src="https://cloud.githubusercontent.com/assets/3941231/15203996/9fad989e-17bd-11e6-86cb-df65c2983626.png">

Fixed on VM-7
