### ISSUE TITLE
Logo à mettre à jour

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-hub#24]
Le logo du GBIF.org est à mettre à jour dans les pages suivantes (dans la partie visiteur en générale je pense) : 
- la recherche (http://recherche.gbif.fr/search)
- les résulats de recherche (http://recherche.gbif.fr/occurrences/search?taxa=felix ; http://recherche.gbif.fr/occurrences/7dcf9a23-1c5a-470f-8be7-678331c1a442)

**Comment by melecoq** [comment]
<img width="1202" alt="screen shot 2016-05-10 at 10 09 00" src="https://cloud.githubusercontent.com/assets/3941231/15155428/3c9e742a-1697-11e6-9372-441957dc775c.png">

Fixed on VM-2
