### ISSUE TITLE
Mauvais lien dans le bouton de retour au résultats de recherche 

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-hub#25]
Le lien de retour au résultats de recherche qui se trouve sur les fiches individuelles d'occurence ne marche pas : il point sur la page elle-même

(http://recherche.gbif.fr/occurrences/eb61ff10-1f62-4b31-a46b-1a05da281630#)

![es portail_ala-visiteur-bouton_retour](https://cloud.githubusercontent.com/assets/12632799/14982947/73726018-113a-11e6-94eb-006f1c140cc7.PNG)

**Comment by melecoq** [comment]
<img width="1237" alt="screen shot 2016-05-10 at 10 06 38" src="https://cloud.githubusercontent.com/assets/3941231/15155357/fa20258a-1696-11e6-94f8-bb549de5c7bf.png">

Fixed on VM-2
