### ISSUE TITLE
Couleur de certains bouton

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-hub#27]
Certains boutons sont bleu ; ne vaudrait-ils pas mieux les mettres en marrons ou comme sur le site internet du GBIF France ?

http://recherche.gbif.fr/occurrences/search?q=text%3Afelis+catus&fq=taxon_name%3A%22Felis+catus%22&fq=month:%2205%22

![capture_73](https://cloud.githubusercontent.com/assets/12632799/15181931/2fed5784-178a-11e6-9ab0-8afaedbad395.PNG)

**Comment by melecoq** [comment]
<img width="698" alt="screen shot 2016-05-12 at 21 44 50" src="https://cloud.githubusercontent.com/assets/3941231/15238256/caa94566-188a-11e6-9be1-a9a677d854ea.png">
<img width="1137" alt="screen shot 2016-05-12 at 21 44 27" src="https://cloud.githubusercontent.com/assets/3941231/15238257/caac7c4a-188a-11e6-8f5d-9116a8b7a300.png">

Fixed on VM-7
