### ISSUE TITLE
Résultats spatiaux vide

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-hub#3]
Pour la recherche avancée d'une espèce de Hibou (Asio Otus), j'ai utilisé la recherche avancé 
![rapport_erreur_4](https://cloud.githubusercontent.com/assets/12632799/14631453/c8ec3a00-0613-11e6-809f-504cf4e56970.PNG)

et j'ai eu 26 résultats mais la carte est vide (même inexistante ; voir ci-dessous). Est-ce parce qu'aucun des 26 enregistrements n'est géo-référencé ?

![rapport_erreur_5](https://cloud.githubusercontent.com/assets/12632799/14631452/c8eaf01e-0613-11e6-9b2b-5a0ff2984432.PNG)

**Comment by CaviereFabien** [comment]
Mea Culpa : lorsque j'ai fait le test, j'ai utilisé le lien du fil rouge, ce qui m'a amené au portail à l'adresse http://185.26.127.140/generic-hub/occurrences/

Dans le portail (http://recherche.gbif.fr/occurrences/), la carte (son encadré) ne s'affiche pas (voir capture d'écran)
![capture_1](https://cloud.githubusercontent.com/assets/12632799/14638043/a667da4e-0635-11e6-9724-b8c69c32b8d4.png)

**Comment by melecoq** [comment]
Même bug que #18
