### ISSUE TITLE
Selection de filtres dans le menu "Narrow your results"

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-hub#4]
Bien que ce soit des cases à cocher, on ne peut pas choisir plusieurs filtres car un clic sur un filtre lance immédiatement la sélection avec ce seul filtre (rapport_erreur_6)
Pour avoir plusieurs filtres actifs, on est obligé de passer par l'option "choose more" et d'utiliser la fenêtre de la capture d'écran rapport_erreur_7
![rapport_erreur_6](https://cloud.githubusercontent.com/assets/12632799/14631633/a63da8c6-0614-11e6-9f01-bf18770efe42.PNG)
![rapport_erreur_7](https://cloud.githubusercontent.com/assets/12632799/14631634/a63f3592-0614-11e6-83c0-5b0a9a04aae2.PNG)

**Comment by melecoq** [comment]
Corrigé dans la version 1.15
