### ISSUE TITLE
message d'erreur en anglais (temps de réponse trop long)

### ISSUE THREAD

**Issue by adelinekerner** [gbiffrance/gbiffrance-hub#44]
Avec une recherche sur une Famille les Sciuridae : 
http://recherche.gbif.fr/occurrences/search?taxa=Sciuridae+#tab_recordsView
Dans la partie graphique sur le premier camembert 
étape 1 cliquer sur le plus gros pourcentage 
étape 2 cliquer sur le bouton rang précédent
et là message d'erreur en anglais sur le temps de réponse
![camenbert2](https://cloud.githubusercontent.com/assets/19606086/15617736/88763c0a-244a-11e6-8b6b-060c14167aae.jpg)

**Comment by melecoq** [comment]
Non reproductible
