### ISSUE TITLE
Sélection des filtres pour affinée les résultats d'une recherche

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-hub#6]
Sur la fenêtre sensé nous indiqués/montré les filtres disponible, on a une fenêtre modale qui charge sans fin. 
![capture_6](https://cloud.githubusercontent.com/assets/12632799/14638423/a2bcf184-0637-11e6-9fe9-cb0544dfd565.png)

**Comment by CaviereFabien** [comment]
Mauvaise version

**Comment by melecoq** [comment]
<img width="1274" alt="screen shot 2016-05-10 at 10 14 34" src="https://cloud.githubusercontent.com/assets/3941231/15155595/057fc0ce-1698-11e6-834b-e44134a1c67c.png">

Fixed on VM-2
