### ISSUE TITLE
Recherche par taxon

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-hub#7]
Lors d'une recherche par taxon (http://185.26.127.140/generic-hub/search#tab_taxaUpload), 

![capture_08](https://cloud.githubusercontent.com/assets/12632799/14638615/597cd57e-0638-11e6-912d-3aa01124fdde.png)

on a une erreur serveur 

![capture_09](https://cloud.githubusercontent.com/assets/12632799/14638616/5a465c8c-0638-11e6-9184-f08a6b3c6ae7.png)

**Comment by melecoq** [comment]
Effectivement, je vais voir si ça vaut le coup de laisser cette fonctionnalité. Je regarderai ça plus tard

**Comment by melecoq** [comment]
Fonctionnalitée retiré.
