### ISSUE TITLE
Tableau partiellement en anglais dans la fiche d'un enregistrement

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-hub#9]
A la fin de la fiche d'un enregistrement (http://recherche.gbif.fr/occurrences/a5187cff-fd92-4f82-85ef-222a62cfdd46), le tableau est partiellement en anglais : nom des tests, les deux menu englobant
![capture_11](https://cloud.githubusercontent.com/assets/12632799/14638736/0e7255e4-0639-11e6-9fac-3ef1d9627965.png)

**Comment by melecoq** [comment]
Voir bug #48
